### ISSUE TITLE
Install gpx-tools

### ISSUE THREAD

**Issue by Pitido** [hamishcoleman/gpx-tools#1]
Hello,

I'm not able to install gpx-tools with Debian Linux.

Can you help, please?

Thank you!

Pietido

**Comment by hamishcoleman** [comment]
Hi!

I develop using Debian, so It *should* work perfectly with Debian, but it has not had a lot of testing outside of my own systems.

What have you tried and what errors are you getting?

**Comment by Pitido** [comment]
Hi Hamisch,


thank you for your fast response.


Under ~/src

git clone https://github.com/hamishcoleman/gpx-tools.git

cd gpx-tools

make


error:


test
make: *** [Makefile:14: all] Fehler 1


I installed all packages which are mentioned in the Makefile manually.

By the way:

Can I use gpx-tools to disassemble gpx-files?

I have a lot of gpx files which contain several tracks and would need one track in one file. The file name should be the the "name" tag from the related track.

Thank you!


Kind regards


Pietido

**Comment by hamishcoleman** [comment]
It seems that I had a bug in that make target - it simply ran the test suite, but I have pushed a fix for that.

There is no tool here for splitting GPX on the track names - it is all based on timestamps (none of my loggers ever generated useful track names, so I have not gone down that path)

That being said, you should be able to write an XML parser that does what you want - The libraries here might not be the simplest starting point, as I have built them in a rather idiomatic way.

**Comment by Pitido** [comment]
Hi Hamisch,

thank you, works perfect now!

Kind regards

Pietido
